<div class="alert alert-block alert-info">
<center>ESTATÍSTICA APLICADA</center>
<center>LISTA 01</center>
<center>ALUNO: Luís Felipe Ferreira Tavares Nonato</center>
</div>

<div class="alert alert-block alert-info">
Questão 1
</div>

## Listas 
    Usadas normalmente para armazenamento de poucos dados.
    Ex: nomes de alunos de uma sala.
    
    Principais caracteristicas: 

        - mutáveis
        - ordenadas
        - heterogêneas
        - indexada por posição
        - delimitada por colchetes [ ]
        

## Dicionários 
    Usados para dados que precisam de maior organização, onde a indexação pode atrapalhar.
    Ex: Lista telefonica.

    Principais caracteristicas: 
    
        - mutáveis
        - não ordenados
        - heterogêneos
        - indexada por chaves
        - delimitada por chaves { }
        
##  ndarray - Numpy

    Usada como uma lista, mas com facilitação na forma de criar e na possibilidade usar para
    operações com os elementos da lista.
    Ex: Listas de salarios e valor recebido por horas extras que precisam ser somadas.
    
    Principais caracteristicas:
        
        - mutáveis
        - ordenadas
        - "heterogêneas" → (upcasting)
        - indexada por posição
        - delimitada por funções da lib numpy


<div class="alert alert-block alert-info">
Questão 2
</div>

Há mais de uma forma importar a biblioteca numpy.

   ## import numpy
        
   - Importa toda a biblioteca numpy. Forma de chamar uma função:
       
       ` numpy.func(parm) `
   
   ## from numpy import function
   
   - Importa apenas uma função da biblioteca numpy. Forma de chamar a função:
       
       ` func(parm) `
       
   ## from numpy import *
   
   - Importa todas as funções da biblioteca numpy, porem pode causar conflito com</br>outras bibliotecas que tenham funções com o mesmo nome. Forma de chamar uma função:
       
       ` func(parm) `
       
   ## import numpy as np
   
   - Importa toda a biblioteca numpy e apelida a lib de np. Forma de chamar uma função:
       
       ` np.func(parm) `
       
       ---
Para saber a versão da biblioteca numpy basta executar o comando abaixo:

In [1]:
pip show numpy

Name: numpy
Version: 1.22.3
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: wxPython
Note: you may need to restart the kernel to use updated packages.


<div class="alert alert-block alert-info">
Questão 3
</div>

- Vetorização

    Diferente de um `for` explicito, a biblioteca numpy <br>
    consegue fazer mais de uma operação ao mesmo tempo, <br>
    aproveitando mais da capacidade do processador, e <br>
    otimizando o codigo, gerando resultados mais rapidos.

<br>

- Broadcasting

    A biblioteca numpy consegue se utilizar de um aritificio,<br>
    para realizar operações entre arrays de tamanhos diferentes,<br>
    por exemplo, uma multiplicação entre um array (3x3) e outro<br>
    array (1x3), resultara em um array (3x3).

<br>

- Fontes

     - [Vetorização](https://medium.com/@leonardopiechacaldeira/guia-explicativo-para-as-bibliotecas-pandas-e-numpy-b061475d874c)
     - [Broadcasting](http://www.opl.ufc.br/pt/post/numpy/#broadcasting)

<div class="alert alert-block alert-info">
Questão 4
</div>

In [2]:
import numpy as np

In [3]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [4]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

<div class="alert alert-block alert-info">
Questão 5
</div>

In [1]:
lista = [
['F','H',5], #1
['M','M',8], #2
['F','P',8], #3
['F','H',6], #4
['M','C',5], #5
['M','H',6], #6
['F','M',8], #7
['F','P',4], #8
['F','H',2], #9
['M','C',6], #10
['F','P',8], #11
['M','M',2], #12
['M','G',4], #13
['M','G',9], #14
['M','M',7], #15
['M','M',1], #16
['F','P',8], #17
['F','G',5], #18
['M','G',9], #19
['M','P',5], #20
['F','M',8], #21
['F','G',6], #22
['M','H',3], #23
['M','M',5], #24
['F','P',5], #25
['F','G',5], #26
['M','C',7], #27
['M','H',4], #28
['F','M',7], #29
['F','P',7], #30
['F','M',6], #31
['M','G',6], #32
['M','H',9], #33
['F','M',8], #34
['M','P',5], #35
['M','G',6], #36
['F','M',7], #37
['M','P',5], #38
['F','M',5], #39
['F','M',5], #40
['F','P',9], #41
['M','M',8]  #42
]

### Dificuldades:

   * Dificil modificação
   * Acesso apenas por indices, tornando confuso entendimento
   * Impossivel fazer operações com elementos da lista

In [2]:
dic = {
'sex':[
'F','M','F','F','M','M','F',
'F','F','M','F','M','M','M',
'M','M','F','F','M','M','F',
'F','M','M','F','F','M','M',
'F','F','F','M','M','F','M',
'M','F','M','F','F','F','M'
],
'mat':[
'H','M','P','H','C','H',
'M','P','H','C','P','M',
'G','G','M','M','P','G',
'G','P','M','G','H','M',
'P','G','C','H','M','P',
'M','G','H','M','P','G',
'M','P','M','M','P','M'
],
'nota':[
5,8,8,6,5,6,8,
4,2,6,8,2,4,9,
7,1,8,5,9,5,8,
6,3,5,5,5,7,4,
7,7,6,6,9,8,5,
6,7,5,5,5,9,8
]}

### Dificuldades:

   * Acesso apenas por elementos, não podendo ver dados de um aluno por completo
   * Impossivel fazer operações com elementos da lista

In [3]:
import numpy as np

npList = np.array([
['F','H',5], #1
['M','M',8], #2
['F','P',8], #3
['F','H',6], #4
['M','C',5], #5
['M','H',6], #6
['F','M',8], #7
['F','P',4], #8
['F','H',2], #9
['M','C',6], #10
['F','P',8], #11
['M','M',2], #12
['M','G',4], #13
['M','G',9], #14
['M','M',7], #15
['M','M',1], #16
['F','P',8], #17
['F','G',5], #18
['M','G',9], #19
['M','P',5], #20
['F','M',8], #21
['F','G',6], #22
['M','H',3], #23
['M','M',5], #24
['F','P',5], #25
['F','G',5], #26
['M','C',7], #27
['M','H',4], #28
['F','M',7], #29
['F','P',7], #30
['F','M',6], #31
['M','G',6], #32
['M','H',9], #33
['F','M',8], #34
['M','P',5], #35
['M','G',6], #36
['F','M',7], #37
['M','P',5], #38
['F','M',5], #39
['F','M',5], #40
['F','P',9], #41
['M','M',8]  #42
])

### Dificuldades:

   * Acesso por indices, tornando confuso entendimento